workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.solvewithsoftware.highwoods
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_credentials
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Create .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "ONESIGNAL_APP_ID=$ONESIGNAL_APP_ID" >> .env
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.$PROJECT_BUILD_NUMBER \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - marc@solvewithsoftware.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      flutter: stable
      java: 17
      groups:
        - app_credentials
    scripts:
      - name: Create .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "ONESIGNAL_APP_ID=$ONESIGNAL_APP_ID" >> .env
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK with Flutter
        script: |
          flutter build apk --release \
            --build-name=1.0.$PROJECT_BUILD_NUMBER \
            --build-number=$PROJECT_BUILD_NUMBER
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release \
            --build-name=1.0.$PROJECT_BUILD_NUMBER \
            --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - marc@solvewithsoftware.com
        notify:
          success: true
          failure: true
